from enum import IntEnum


class MigrationEvent(IntEnum):
    LEGACY_CODE_ANALYSIS = 1
    IDENTIFIED_ENTITIES = 2
    TARGET_CODE_ANALYSIS = 11
    ASSETS_AND_CONFIGURATION = 3
    TECHNICAL_DOCUMENTATION = 4
    FUNCTIONAL_DOCUMENTATION = 5
    ARCHITECTURAL_DETAILS = 6
    RISK_ASSESSMENT = 7
    MIGRATION_PLAN = 8
    MIGRATION_PROGRESS = 9
    COMPLETION_SUMMARY = 10
